defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /posts/:title/
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-archives

url: "https://sandstormnick.github.io/"
baseurl: "/Jekyll-Theme-Verdant"

exclude:
  - docker-compose.yml
  - assets/images/attribution.txt

sass:
  quiet_deps: true
  load_paths:
    - /home/runner/work/Jekyll-Theme-Verdant/Jekyll-Theme-Verdant/vendor/bundle/ruby/3.1.0/gems/bootstrap-5.3.8/assets/stylesheets

jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: category
    tag: tag
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'